name: 🚀 Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      BUILD_SOURCE_DIR: .
      BUILD_ARTIFACT_STAGING_DIR: build/
      HOST_SERVER: ftp.maps.luxovi.us
    steps:
      - name: 🛎️ Checkout project
        uses: actions/checkout@v3

      - name: 🖱️ Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: 📥 Install back-end dependencies
        run: composer install --no-interaction --prefer-dist --no-dev --optimize-autoloader

      - name: 🖱️ Set Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: 📥 Install front-end dependencies
        run: npm ci --ignore-scripts

      - name: 🔨 build front-end
        run: npm run build

      - name: 🗑️ Remove storage directory
        run: rm -rf storage
        
      - name: 📁 Create build directory
        run: mkdir ${{ env.BUILD_ARTIFACT_STAGING_DIR }}
          
      - name: 🗄️ ZIP Build
        uses: TheDoctor0/zip-release@0.6.1
        with:
          filename: ${{ env.BUILD_ARTIFACT_STAGING_DIR }}build.zip
          path: ${{ env.BUILD_SOURCE_DIR }}
          exclusions: 'storage/* build/* node_modules/*'

      - name: ➗ Calculate checksum
        run: openssl md5 ${{ env.BUILD_ARTIFACT_STAGING_DIR }}build.zip | cut -d" " -f2 > ${{ env.BUILD_ARTIFACT_STAGING_DIR }}checksum.txt

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ env.HOST_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ${{ env.BUILD_ARTIFACT_STAGING_DIR }}
